<?php
use Drupal\Core\Access\AccessResult;
/**
 * Implements hook_entity_view_alter().
 */


/**
 * Implements hook_node_access().
 */
function coopernetaccess_node_access($node, $op, $account) {
  //dpm("##########################");
  // Attention le piège est que le superadmin ne passe pas dans ce hook
  if($node->getType() == "book" && !$account->isAuthenticated()) {
    return AccessResult::forbidden();
  }
}