<?php
use Drupal\Core\Form\FormStateInterface;
/**
 * Implements hook_form_alter().
 */
function memo_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  //dpm($form_id);
  // Adding custom validation for the welcome page type field.
  if ($form_id == 'node_carte_edit_form' || $form_id == 'node_carte_form') {
    $form['#attached']['library'][] = 'memo/questiontitle';
    $form['#attached']['drupalSettings']['memo']['questiontitle'] ['parametre'] = 'monparametre';
    return $form;
  }
}